-- British and American spelling find each other (and tags use American).
--
-- Typing "tumour" found only "tumour…", and "tumor" missed every UK-spelled
-- abstract (Lancet, BJC, CRUK-funded work). Semantic search already copes;
-- keyword search and the filter menus didn't.
--
--   1. spelling_variants: whole-word British -> American pairs from VarCon
--      (the SCOWL spell-checker lists), loaded by the next migration. Whole
--      words, not patterns: a lookup can't turn "colour" into a match for
--      "colorectal" or misspell "centred", which hand-written fragment rules
--      did. Generated by scripts/varcon_to_sql.py; notices in
--      THIRD_PARTY_NOTICES.md.
--   2. us_spelling(text): every word swapped for its American spelling.
--      spelling_alternatives(word): the word's other spelling(s), either way.
--   3. prefix_tsquery — behind every keyword search (Papers, the home search
--      box, the Atlas MCP) — adds each typed word's other spelling as a whole
--      word: (tumour:* | tumor). The typed word keeps its prefix match.
--      search_papers / search_papers_count build it once per search (it now
--      reads a table, so Postgres no longer folds it to a constant), and fold a
--      ?tag= value the way stored tags are folded, so old UK-spelled links work.
--   4. team_tags / team_venues match each typed word as the start of a word
--      in the name, or its other spelling as a whole word: "tumour" finds
--      tumor-microenvironment, "colour" doesn't find colorectal-cancer.
--      Authors are names and are left as typed.
--   5. Tags use American spelling: clean_tags folds each word to US spelling
--      before merges apply; tag_aliases only accepts US-spelled entries; and
--      clean_tag_map lets the tagger clean a reply with the same rules.

-- Earlier drafts of this migration reached local databases.
drop function if exists public.uk_spelling(text);
drop function if exists public.spelling_rules();
drop function if exists public.clean_tag_map(text[]);

create table if not exists public.spelling_variants (
    uk text primary key check (uk ~ '^[a-z]+$'),
    us text not null    check (us ~ '^[a-z]+$' and us <> uk)
);
create index if not exists spelling_variants_us_idx on public.spelling_variants (us);

comment on table public.spelling_variants is
    'British -> American word spellings, filtered from VarCon. See 20261010180000_spelling_variants.sql.';

-- Reference data every search reads (prefix_tsquery runs as the caller).
alter table public.spelling_variants enable row level security;
drop policy if exists "spelling variants are public" on public.spelling_variants;
create policy "spelling variants are public" on public.spelling_variants
    for select using (true);
grant select on public.spelling_variants to anon, authenticated, service_role;
grant insert, update, delete on public.spelling_variants to service_role;

-- Lowercase text with each word in American spelling; separators kept.
create or replace function public.us_spelling(p_text text)
returns text
language sql
stable
set search_path = public
as $$
    select coalesce(string_agg(coalesce(v.us, m.tok[1]), '' order by m.ord), '')
    from regexp_matches(lower(coalesce(p_text, '')), '[a-z0-9]+|[^a-z0-9]+', 'g')
         with ordinality as m(tok, ord)
    left join public.spelling_variants v on v.uk = m.tok[1];
$$;

-- The other spelling(s) of one lowercase word, in either direction.
create or replace function public.spelling_alternatives(p_word text)
returns setof text
language sql
stable
set search_path = public
as $$
    select us from public.spelling_variants where uk = p_word
    union
    select uk from public.spelling_variants where us = p_word;
$$;

-- Reissued from 20260712130000_paper_search.sql. Each typed word keeps its
-- prefix match; its other spelling is added as a whole word, so "colour"
-- adds "color" (not color:*, which would match colorectal). Stable now, as it
-- reads spelling_variants; a word with no variant gives the same query as
-- before.
create or replace function public.prefix_tsquery(p_q text)
returns tsquery
language sql
stable
set search_path = public
as $$
    select to_tsquery(
        'english',
        (select string_agg(
                    '(' || tok || ':*'
                        || coalesce((select string_agg(' | ' || alt, '')
                                     from public.spelling_alternatives(tok) as alt), '')
                        || ')',
                    ' & ')
         from unnest(regexp_split_to_array(lower(coalesce(p_q, '')), '[^a-z0-9]+')) as tok
         where tok <> '')
    );
$$;

-- Does p_name match what was typed? The old substring match, or: every typed
-- word starts a word of the name, or its other spelling is a whole word of it.
-- A query with no letters or digits ("-", "β") gets only the substring match;
-- otherwise "every word matches" would be vacuously true for every name.
create or replace function public.name_matches(p_name text, p_q text)
returns boolean
language sql
stable
set search_path = public
as $$
    with typed as (
        select w, array(select public.spelling_alternatives(w)) as alts
        from unnest(regexp_split_to_array(lower(coalesce(p_q, '')), '[^a-z0-9]+')) as w
        where w <> ''
    )
    select coalesce(p_q, '') = ''
        or position(lower(p_q) in lower(p_name)) > 0
        or (
            exists (select 1 from typed)
            and not exists (
                select 1
                from typed t
                where not exists (
                    select 1
                    from unnest(regexp_split_to_array(lower(p_name), '[^a-z0-9]+')) as nw
                    where nw like t.w || '%' or nw = any (t.alts)
                )
            )
        );
$$;

-- Reissued from 20261010120000_author_filter.sql; only the p_q match changes.
-- Counted first, matched after: name_matches runs once per distinct tag, not
-- once per post.
create or replace function public.team_tags(
    p_team  uuid,
    p_q     text default null,
    p_limit int  default null
)
returns table(tag text, n int)
language sql
stable
as $$
    select g.tag, g.n
    from (
        select t.tag, count(*)::int as n
        from public.paper_posts pp
        join public.papers p on p.id = pp.paper_id
        cross join lateral jsonb_array_elements_text(public.post_tags(pp.tags, p.tags)) as t(tag)
        where pp.team_id = p_team
        group by t.tag
    ) g
    where public.name_matches(g.tag, p_q)
    order by g.n desc, g.tag
    limit p_limit;
$$;

create or replace function public.team_venues(
    p_team  uuid,
    p_q     text default null,
    p_limit int  default null
)
returns table (venue text, count bigint)
language sql
stable
as $$
    select g.venue, g.count
    from (
        select p.venue, count(*) as count
        from public.paper_posts pp
        join public.papers p on p.id = pp.paper_id
        where pp.team_id = p_team
          and p.venue is not null
          and p.venue <> ''
        group by p.venue
    ) g
    where public.name_matches(g.venue, p_q)
    order by g.count desc, g.venue
    limit p_limit;
$$;

-- Reissued from 20261010140000_tag_hygiene.sql: each word of a tag is folded
-- to US spelling after normalising and before merges apply.
create or replace function public.clean_tags(p_tags jsonb)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
    select coalesce(jsonb_agg(s.tag order by s.first_pos), '[]'::jsonb)
    from (
        select coalesce(a.canonical, n.tag) as tag, min(e.ord) as first_pos
        from jsonb_array_elements_text(
                 case when jsonb_typeof(p_tags) = 'array' then p_tags else '[]'::jsonb end
             ) with ordinality as e(raw, ord)
        cross join lateral (select public.us_spelling(public.normalise_tag(e.raw)) as tag) n
        left join public.tag_aliases a on a.alias = n.tag
        where n.tag <> ''
        group by 1
    ) s;
$$;

-- What each raw tag becomes when stored, and whether some paper already
-- carries that tag: lets the tagger judge a reply with the database's rules
-- (spelling, merges) in one round trip, instead of a copy of them.
create or replace function public.clean_tag_map(p_tags text[])
returns table(raw text, cleaned text, known boolean)
language sql
stable
set search_path = public
as $$
    select c.raw, c.cleaned,
           c.cleaned is not null
           and exists (select 1 from public.papers p where p.tags ? c.cleaned)
    from (
        select r as raw, public.clean_tags(jsonb_build_array(r)) ->> 0 as cleaned
        from unnest(p_tags) as r
    ) c;
$$;

revoke execute on function public.clean_tag_map(text[]) from public, anon, authenticated;
grant  execute on function public.clean_tag_map(text[]) to service_role;

-- Reissued from 20261010120000_author_filter.sql. The tsquery and the folded
-- tag are computed once per call (a materialized CTE): prefix_tsquery reads
-- spelling_variants now, so Postgres would otherwise re-run it per row, up to
-- four times. p_tag goes through clean_tags, so ?tag=tumour-microenvironment
-- finds the papers now tagged tumor-microenvironment.
drop function if exists public.search_papers(uuid, text, text, int, int, text, text, text, text);
drop function if exists public.search_papers_count(uuid, text, text, text, text, text);

create or replace function public.search_papers(
    p_team   uuid,
    p_q      text default '',
    p_tag    text default null,
    p_limit  int  default 30,
    p_offset int  default 0,
    p_sort   text default 'shared',
    p_venue  text default null,
    p_status text default null,  -- 'unread' | 'reading' | 'read' | 'saved'
    p_author text default null
)
returns setof public.paper_posts
language sql
stable
as $$
    with q as materialized (
        select public.prefix_tsquery(p_q) as tsq,
               coalesce(public.clean_tags(jsonb_build_array(p_tag)) ->> 0, p_tag) as tag
    )
    select pp.*
    from q
    cross join public.paper_posts pp
    join public.papers p on p.id = pp.paper_id
    left join public.paper_status ps
           on ps.paper_id = pp.paper_id
          and ps.team_id  = pp.team_id
          and ps.user_id  = auth.uid()
    where pp.team_id = p_team
      and (q.tag is null or public.post_tags(pp.tags, p.tags) ? q.tag)
      and (p_venue is null or p.venue = p_venue)
      and (p_author is null or p.authors ? p_author)
      and (
        p_status is null
        -- "saved" asks the membership axis, independently of progress: a paper
        -- central to your project stays saved after you have read it.
        or (p_status = 'saved' and coalesce(ps.saved, false))
        -- No row at all is unread: never opened, never saved.
        or (p_status = 'unread' and (ps.status is null or ps.status = 'unread'))
        or (p_status in ('reading', 'read') and ps.status = p_status)
      )
      and (
        q.tsq is null
        or to_tsvector('english',
             coalesce(p.title, '') || ' ' || coalesce(p.abstract, '') || ' ' || coalesce(p.authors::text, ''))
           @@ q.tsq
      )
    order by
      (case
         when q.tsq is null then 0
         else ts_rank(
                to_tsvector('english',
                  coalesce(p.title, '') || ' ' || coalesce(p.abstract, '') || ' ' || coalesce(p.authors::text, '')),
                q.tsq
              )
       end) desc,
      (case when p_sort = 'published' then p.published_at end) desc nulls last,
      pp.posted_at desc,
      pp.id desc
    limit  greatest(coalesce(p_limit, 30), 0)
    offset greatest(coalesce(p_offset, 0), 0);
$$;

create or replace function public.search_papers_count(
    p_team   uuid,
    p_q      text default '',
    p_tag    text default null,
    p_venue  text default null,
    p_status text default null,
    p_author text default null
)
returns integer
language sql
stable
as $$
    with q as materialized (
        select public.prefix_tsquery(p_q) as tsq,
               coalesce(public.clean_tags(jsonb_build_array(p_tag)) ->> 0, p_tag) as tag
    )
    select count(*)::int
    from q
    cross join public.paper_posts pp
    join public.papers p on p.id = pp.paper_id
    left join public.paper_status ps
           on ps.paper_id = pp.paper_id
          and ps.team_id  = pp.team_id
          and ps.user_id  = auth.uid()
    where pp.team_id = p_team
      and (q.tag is null or public.post_tags(pp.tags, p.tags) ? q.tag)
      and (p_venue is null or p.venue = p_venue)
      and (p_author is null or p.authors ? p_author)
      and (
        p_status is null
        or (p_status = 'saved' and coalesce(ps.saved, false))
        or (p_status = 'unread' and (ps.status is null or ps.status = 'unread'))
        or (p_status in ('reading', 'read') and ps.status = p_status)
      )
      and (
        q.tsq is null
        or to_tsvector('english',
             coalesce(p.title, '') || ' ' || coalesce(p.abstract, '') || ' ' || coalesce(p.authors::text, ''))
           @@ q.tsq
      );
$$;

grant execute on function public.search_papers(uuid, text, text, int, int, text, text, text, text) to authenticated;
grant execute on function public.search_papers_count(uuid, text, text, text, text, text)            to authenticated;

-- Reissued from 20261010140000_tag_hygiene.sql: also refuse a merge whose
-- alias or kept tag isn't in American spelling (a UK alias could never match,
-- since tags are folded first; a UK kept tag would bring UK spelling back).
create or replace function public.tag_aliases_flat()
returns trigger
language plpgsql
set search_path = public
as $$
begin
    if new.alias <> public.us_spelling(new.alias) or new.canonical <> public.us_spelling(new.canonical) then
        raise exception 'tag_aliases: "%" -> "%" must use American spelling',
            new.alias, new.canonical using errcode = 'check_violation';
    end if;
    if exists (select 1 from public.tag_aliases where alias = new.canonical) then
        raise exception 'tag_aliases: "%" is itself merged into another tag; point "%" at that tag instead',
            new.canonical, new.alias using errcode = 'check_violation';
    end if;
    if exists (select 1 from public.tag_aliases where canonical = new.alias and alias <> new.alias) then
        raise exception 'tag_aliases: "%" is the kept tag of other merges and can''t be merged away',
            new.alias using errcode = 'check_violation';
    end if;
    return new;
end;
$$;
