-- First reviewed batch of tag merges (85 groups, 106 tags), proposed by
-- api/propose_tag_merges.py against the live library (1,471 distinct tags)
-- and approved by Ellen on 2026-10-10. Mostly plurals, hyphenation variants
-- and abbreviations (scrna-seq, nsclc, cytof, llm); a few synonyms.
--
-- Inserting the aliases makes every future write use the kept tag (the
-- clean_tags trigger, 20261010140000_tag_hygiene.sql); apply_tag_cleanup()
-- then rewrites the tags already stored on papers, lab posts, follows and the
-- undo archive. tag_aliases' flat-table trigger rejects any chain, so a bad
-- row fails the whole migration rather than half-applying.

insert into public.tag_aliases (alias, canonical) values
    ('scrna-seq', 'single-cell-rna-seq'),
    ('single-cell-rna-sequencing', 'single-cell-rna-seq'),
    ('tertiary-lymphoid-organs', 'tertiary-lymphoid-structures'),
    ('foundation-models', 'foundation-model'),
    ('computational-methods', 'computational-method'),
    ('spatial-multiomics', 'spatial-multi-omics'),
    ('immune-checkpoint-therapy', 'immune-checkpoint-blockade'),
    ('llm', 'large-language-models'),
    ('biomarker', 'biomarkers'),
    ('multiplex-imaging', 'multiplexed-imaging'),
    ('multiplex-tissue-imaging', 'multiplexed-imaging'),
    ('multiomics', 'multi-omics'),
    ('pan-cancer-analysis', 'pan-cancer'),
    ('clinical-trials', 'clinical-trial'),
    ('antibody-drug-conjugate', 'antibody-drug-conjugates'),
    ('multi-modal-learning', 'multimodal-learning'),
    ('immune-escape', 'immune-evasion'),
    ('immune-checkpoint-inhibitor', 'immune-checkpoint-inhibitors'),
    ('immune-checkpoint-inhibition', 'immune-checkpoint-inhibitors'),
    ('checkpoint-inhibitors', 'immune-checkpoint-inhibitors'),
    ('checkpoint-inhibitor', 'immune-checkpoint-inhibitors'),
    ('graph-neural-network', 'graph-neural-networks'),
    ('therapy-resistance', 'drug-resistance'),
    ('treatment-resistance', 'drug-resistance'),
    ('therapeutic-resistance', 'drug-resistance'),
    ('mouse-models', 'mouse-model'),
    ('multiplexed-immunofluorescence', 'multiplex-immunofluorescence'),
    ('prognostic-biomarker', 'prognostic-biomarkers'),
    ('cell-cell-interactions', 'cell-cell-communication'),
    ('cell-cell-interaction', 'cell-cell-communication'),
    ('xenium-in-situ', 'xenium'),
    ('ai-agent', 'ai-agents'),
    ('crispr-screening', 'crispr-screen'),
    ('cancer-evolution', 'tumor-evolution'),
    ('spatial-domain-detection', 'spatial-domain-identification'),
    ('copy-number-alteration', 'copy-number-alterations'),
    ('generative-models', 'generative-model'),
    ('generative-modeling', 'generative-model'),
    ('deep-generative-model', 'generative-model'),
    ('deep-generative-models', 'generative-model'),
    ('multi-modal-integration', 'multimodal-integration'),
    ('multimodal-data-integration', 'multimodal-integration'),
    ('multimodal-fusion', 'multimodal-integration'),
    ('chemoresistance', 'chemotherapy-resistance'),
    ('cytof', 'mass-cytometry'),
    ('he-image-analysis', 'h&e-imaging'),
    ('h&e-image-analysis', 'h&e-imaging'),
    ('nsclc', 'non-small-cell-lung-cancer'),
    ('vision-language-models', 'vision-language-model'),
    ('cdk4-6-inhibitors', 'cdk4-6-inhibitor'),
    ('cdk4/6-inhibitor', 'cdk4-6-inhibitor'),
    ('ffpe', 'ffpe-tissue'),
    ('lightsheet-microscopy', 'light-sheet-microscopy'),
    ('tgf-beta', 'tgf-beta-signaling'),
    ('diffusion-model', 'diffusion-models'),
    ('immune-cell-infiltration', 'immune-infiltration'),
    ('cancer-therapy', 'cancer-therapeutics'),
    ('cancer-treatment', 'cancer-therapeutics'),
    ('cancer-detection', 'cancer-diagnosis'),
    ('software-tools', 'software-tool'),
    ('single-nucleus-transcriptomics', 'single-nucleus-rna-seq'),
    ('cell-typing', 'cell-type-annotation'),
    ('cell-type-classification', 'cell-type-annotation'),
    ('cell-classification', 'cell-type-annotation'),
    ('neurodegenerative-disease', 'neurodegeneration'),
    ('pathology-foundation-models', 'pathology-foundation-model'),
    ('brain-metastases', 'brain-metastasis'),
    ('tissue-microarrays', 'tissue-microarray'),
    ('anti-tumor-immunity', 'antitumor-immunity'),
    ('real-world-data', 'real-world-evidence'),
    ('real-world-study', 'real-world-evidence'),
    ('car-t-cell-therapy', 'car-t-therapy'),
    ('residual-disease', 'minimal-residual-disease'),
    ('cancer-dormancy', 'tumor-dormancy'),
    ('intra-tumoral-heterogeneity', 'intratumor-heterogeneity'),
    ('dimension-reduction', 'dimensionality-reduction'),
    ('cranial-bone-marrow', 'skull-bone-marrow'),
    ('immunosurveillance', 'immune-surveillance'),
    ('virtual-spatial-transcriptomics', 'spatial-transcriptomics-prediction'),
    ('protein-language-models', 'protein-language-model'),
    ('gut-microbiota', 'gut-microbiome'),
    ('image-translation', 'image-to-image-translation'),
    ('immunoprofiling', 'immune-profiling'),
    ('cancer-metabolism', 'tumor-metabolism'),
    ('precancerous-lesions', 'premalignant-lesions'),
    ('cgas-sting-pathway', 'sting-pathway'),
    ('brca1-brca2', 'brca-mutations'),
    ('target-discovery', 'drug-target-discovery'),
    ('therapeutic-target-discovery', 'drug-target-discovery'),
    ('spatially-aware-clustering', 'spatial-clustering'),
    ('immunopeptidome', 'immunopeptidomics'),
    ('vegf-c-signaling', 'vegf-c'),
    ('scientific-integrity', 'research-integrity'),
    ('cancer-classification', 'tumor-classification'),
    ('dependency-mapping', 'gene-dependency-mapping'),
    ('intratumor-microbiome', 'tumor-microbiome'),
    ('bioinformatics-tools', 'bioinformatics-tool'),
    ('knowledge-distillation', 'model-distillation'),
    ('trajectory-analysis', 'trajectory-inference'),
    ('immune-suppression', 'immunosuppression'),
    ('spatial-single-cell-analysis', 'single-cell-spatial-analysis'),
    ('single-cell-spatial', 'single-cell-spatial-analysis'),
    ('chromosome-instability', 'chromosomal-instability'),
    ('protocols', 'protocol'),
    ('parp-inhibition', 'parp-inhibitors'),
    ('graph-attention-network', 'graph-attention-networks');

select * from public.apply_tag_cleanup();
